### ISSUE TITLE
Widgets are too small on the tablet for precision use by human fingers

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/mercurymobile#20]
Examples include the number incrementer and the date picker (both browser defaults at the moment)
Possible solution: find and use 3rd party widgets

**Comment by aaronstephenson** [comment]
@hans what do you think of these freebies in the Ionic marketplace?
For number fields: https://market.ionic.io/plugins/morph-carousel
For date fields: https://market.ionic.io/plugins/ionicdatepicker or https://market.ionic.io/plugins/onezone-datepicker

**Comment by HansVraga** [comment]
I like the ionic datepicker.

For number fields, on Android you can specify numeric input and the keyboard becomes just a number pad. Is something like that available in ionic? I think the carousel you found is easier to use than a tiny numeric input, but ideally a large number pad I think is more striaghtforward and quick.

**Comment by HansVraga** [comment]
https://github.com/ionic-team/ionic/issues/10161 seems to indicate this is a thing on at least iOS and Android.

**Comment by aaronstephenson** [comment]
Yeah, I would choose to use the number pad, but the Mercury team isn't using this as a native app, just a plain web app. So no dice. Gotta use a widget.

**Comment by aaronstephenson** [comment]
Turns out those two datepickers I linked are for AngularJS. Ugh.

Ionic 3 has a built-in date picker: https://ionicframework.com/docs/components/#datetime

Thoughts?

**Comment by aaronstephenson** [comment]
Then for the number fields (depth and rep) I could just use the built-in list:

https://ionicframework.com/docs/components/#list-no-lines

**Comment by HansVraga** [comment]
I'm a fan of the built in date picker. Simple, and quick.

**Comment by HansVraga** [comment]
List for numbers will work if they are only inputting integers or have a set number of significant digits. How painful is the current input?

**Comment by aaronstephenson** [comment]
I have implemented the built-in date picker for both date and time fields. For number fields, I will use a free-form text input box (which will also validate any data entered), because the values will not always be integers.
