### ISSUE TITLE
Re-consolidate Sample and Bottle data onto one page

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/mercurymobile#33]
Lab staff would prefer bottle data to be re-consolidated onto the sample page, similar to how it already appears on their paper forms. They were originally separated due to size concerns on small devices (too many fields to fit in one page), but with the plan to move some bottle fields into the sample "header" section, there will probably be enough room on the page for all the fields.

**Comment by ehaberman-usgs** [comment]
Complete
