### ISSUE TITLE
Move Filter Type field into Sample header

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/mercurymobile#34]
Currently this field is on each bottle, but lab staff say that it can be moved to the Sample "header" section (similar to the Acid field) and represent the filter type value for all the listed bottles.

**Comment by ehaberman-usgs** [comment]
Complete

**Comment by aaronstephenson** [comment]
I think I might not have been 100% clear on this one. The filter and acid fields are to be moved into the sample "header" section purely for the convenience of the user. The "filter" field belongs to each samplebottle, not to the sample. Ditto for the "preservation_acid" field. Those fields should not be included in the sample object, as they appear to be in this screen cap:

![sample_fields_bug](https://user-images.githubusercontent.com/8713712/37122652-02e675f0-2227-11e8-99b2-d8954ebcac48.PNG)

The way I attempted to accomplish this with acids was to loop through each samplebottle record, then populate the "convenience" field with the first encountered acid value. Then on save, loop through the samplebottles and assign the selected acid value from that "convenience" field to any samplebottle record that had "preservation_type" set to "Acidification". No samplebottle without that preservation type should have an acid assigned to it.

The case of fitlers is a bit more straightforward, since any value selected from a "convenience" field in the "header" should be applied to all samplebottles. This can be accomplished with looping through each samplebottle record, then populate the "convenience" field with the first encountered filter value. And then on save, just populate all related samplebottles with the selected filter value.

**Comment by aaronstephenson** [comment]
Fixed
