### ISSUE TITLE
Bulk Update Acids

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/mercurymobile#35]
Lab staff would like to select several samples in the Sample List page and bulk update the acid in all the selected children bottles. This might be accomplished by a simple button on the Sample List page that pops up a modal for the user to choose a new acid value for the selected samples.

**Comment by ehaberman-usgs** [comment]
Complete

**Comment by aaronstephenson** [comment]
Confirmed that the acid update happens.

However, after a successful update, the checked checkboxes ought to be unchecked (in other words, no checkboxes ought to be checked). Alternately, provide a button to "unselect all" (with a corresponding "select all" button for completeness). What are your thoughts on either approach?

**Comment by ehaberman-usgs** [comment]
Complete:

- added select / unselect all buttons above and below list
- after bulk update, unselect all
