### ISSUE TITLE
Allow users to "create" bottles

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/mercurymobile#37]
Allow users to enter free text in the bottle name field. If the entered value does not match an existing bottle name, simply warn the user with a modal popup and make them confirm that they definitely want to add the new value as a new bottle.

**Comment by aaronstephenson** [comment]
The new sample bottle does indeed show up in the container list and in the _pouchdb_samplebottles DB, but does not appear when the user exits the sample, then re-opens the sample. In this screen cap example, I saved three sample bottles, one of which (ZZZ001A) was manually created (not in the official bottle list), and which doesn't appear to have been saved to the sample's samplebottle array:

![sample_bug_missing_bottle](https://user-images.githubusercontent.com/8713712/37122433-2367ed46-2226-11e8-808e-ed115230774e.PNG)

**Comment by ehaberman-usgs** [comment]
Failed to hook the ID into sample bottles -- fixed.
