### ISSUE TITLE
Replace the date "roller" widget with a date picker

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/mercurymobile#38]
The default Ionic data picker is a number roller, and the lab staff don't like it. They would prefer a traditional calendar date picker.

**Comment by aaronstephenson** [comment]
I started implementing the [ionic2-date-picker](https://github.com/shangyilim/ionic2-date-picker) but haven't finished it yet.

**Comment by ehaberman-usgs** [comment]
Complete.

Update form with the latest version of the ionic2-date-picker module
