### ISSUE TITLE
Samplebottle Field Bugs

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/mercurymobile#40]
I noticed that each samplebottle record is getting assigned an acid ("preservation_acid") value on a sample that has an acid selected in the header section, regardless of whether a particular samplebottle has its "preservation_type" value set to "Acidication" of not. See #34 for a closely related issue.

Additionally, I'm seeing fields whose data types should be Number containing String values.

As seen in this screen cap:

![sample_bottles_bugs](https://user-images.githubusercontent.com/8713712/37123166-d381d6f4-2228-11e8-9483-ba19067c2e59.PNG)

**Comment by ehaberman-usgs** [comment]
Fixed!
