### ISSUE TITLE
Make full use of available space

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/mercurymobile#42]
This is more of a quibble than a bug, but it would be nice to use the full available space for each field. In particular, I'm thinking of the Analysis and Preservation widgets:

![sample_bottle_space_usage](https://user-images.githubusercontent.com/8713712/37123509-21d45c18-222a-11e8-818e-9a676765c8c2.PNG)

**Comment by ehaberman-usgs** [comment]
I had this resolved :/  Hmmm .... investigating.

**Comment by ehaberman-usgs** [comment]
I used the /build folder, which is overwritten at ionic serve - fixed.
