### ISSUE TITLE
Sites List is Duplicated

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/mercurymobile#45]
When a sample is opened, the sites list is getting duplicated.

![image](https://user-images.githubusercontent.com/8713712/37124307-5b33e5d4-222d-11e8-8daf-977e608b76ea.png)

I think it's because of line 228 of sample-detail.ts:

![image](https://user-images.githubusercontent.com/8713712/37124283-39e53aa4-222d-11e8-8fae-d01a74c22863.png)

And then line 397:

![image](https://user-images.githubusercontent.com/8713712/37124357-8f580016-222d-11e8-8700-d4744e90effb.png)

**Comment by ehaberman-usgs** [comment]
I can't reproduce -- will Slack you tomorrow and we can figure out why

**Comment by aaronstephenson** [comment]
I just pulled your latest commit, and am seeing the same thing:
![image](https://user-images.githubusercontent.com/8713712/37215092-997e2e8a-237c-11e8-82ef-37f0066e7dd1.png)

**Comment by aaronstephenson** [comment]
Fixed.
